### ISSUE TITLE
Feature Request - Patient role

### ISSUE THREAD

**Issue by MrYogi** [HospitalRun/hospitalrun-frontend#1034] opened 2017-03-28 08:55 UTC
I am new to Hospitalrun, Is there any way to access patient data history for patient role?
if not please consider as feature request.
thanks

**Comment by jkleinsc** [comment] 2017-03-28 16:26
@MrYogi could explain further what you are looking for?  Do you mean for a patient to view their own data or for clinical staff to view the history of a specific patient?  HospitalRun allows clinical staff to view patient data, but there currently isn't a way for patients to view their own data.

**Comment by emadehsan** [comment] 2017-03-28 19:16
@MrYogi there is a feature request here #979 about the same functionality.

**Comment by MrYogi** [comment] 2017-03-29 05:50
yes same as[ #979 ](https://github.com/HospitalRun/hospitalrun-frontend/issues/979)

**Comment by emadehsan** [comment] 2017-03-29 13:12
@MrYogi then you might close this issue.

**Comment by jkleinsc** [comment] 2017-03-29 13:18
Closing as duplicate of #979

**Closed by jkleinsc** 2017-03-29 13:18 UTC
