### ISSUE TITLE
Can't visit Users page under Administration (session expired), and then locked out of system until cookies are deleted

### ISSUE THREAD

**Issue by jonathan8464** [HospitalRun/hospitalrun-frontend#1077] opened 2017-05-03 20:18 UTC
**Expected behavior:**
Choosing "Administration > Users" in the menu should show UI to manage users.

**Actual behavior:**
I get a pop-up saying that the session is expired. Logging in again shows the same error immediately (without clicking on the menu). The only way to be able to login again is to delete all cookies.

**Steps to reproduce:**
1. New development env on Mac OS X 10.11 (using instructions on main page). This doesn't reproduce at beta.hospitalrun.io, so obviously a dev related issue
2. Login using hradmin/test
3. Go to Administration > Users

**Screenshots (if applicable):**
![image](https://cloud.githubusercontent.com/assets/26964551/25679474/2878aab8-3056-11e7-9553-b893ec4ea724.png)

**OS and Browser:**
Mac OS X 10.11
Chrome 57.0.2987.133
Using HR 0.9.18 (fetched today)
CouchDB 1.6.1

**Comment by TBuc** [comment] 2017-05-03 20:54
I've regularly been experiencing the same issue. Sorry I had no time to report it yet.

@jonathan8464 please note that the session is not actually expired and if you click on some menu on the left (other than Administration) the popup will disappear. Does not solve the problem, but makes it faster to re-gain control over the application.

**Comment by adeolabadmus** [comment] 2017-05-03 21:39
@jonathan8464 @TBuc 

This issue has been reported in #953, it's caused by a bug in CouchDB 2.0. You can change your CouchDB installation to 1.6, and things would work just fine.

**Comment by jonathan8464** [comment] 2017-05-03 21:57
@adeolabadmus I forgot to write that I am using CouchDB 1.6.1. I edited my original post to reflect that. You are right that this is the same bug as #953, and I see there is a comment there now by someone who is experiencing it with 1.6 too. Should I close this issue as duplicate or wait with it? Maybe I can help reproduce.

**Comment by TBuc** [comment] 2017-05-04 08:03
@adeolabadmus awesome, you're right - that's why I did not report it before! I had completely forgot about such issue.
Thank you!

**Comment by jkleinsc** [comment] 2017-05-09 17:26
I have a fix for this issue and it is different from #953, so we will leave it open until the fix is ready.

**Closed** 2017-05-18 00:41 UTC

**Comment by chinmaybhatk** [comment] 2017-05-30 09:28
this issue is still exist..i am facing this problem.. I am using CouchDB 1.6.1

**Comment by waleplanet** [comment] 2017-07-12 08:52
I still have the sane error after trrying the offline fixes using CouchDB 1.6.1
