### ISSUE TITLE
Datepickers not working in Chrome

### ISSUE THREAD

**Issue by cmwebby** [HospitalRun/hospitalrun-frontend#445] opened 2016-05-07 09:30 UTC
**Expected behavior:**

- Clicking a date in the date picker should show selected date in the input box. 
- Clicking the arrows should move to next month. 

**Actual behavior:**
In chrome, when a date or arrow in the date picker is clicked the date picker disappears. It does not show the selected date in the input box. 

*It works fine in firefox and Microsoft Edge*

**Steps to reproduce:**

1. Open Google Chrome
2.Navigate to a page with a date picker. e.g http://localhost:4200/#/patients/edit/new
3.Use date picker

**OS and Browser:**
OS: Windows 10
Browser: Google Chrome Version 50.0.2661.94 m

**Comment by jkleinsc** [comment] 2016-05-09 14:50
@cmwebby I just tested in Windows 10/  Google Chrome Version 50.0.2661.94 m and the date picker works properly for me.  Is it possible you have a chrome extension which is interfering with the date picker?  Can you try running Chrome in Incognito mode which should disable your extensions and test to see if it works then?

**Comment by cmwebby** [comment] 2016-05-09 15:23
@jkleinsc I just tried in incognito that and it still didn't work unfortunately . I also tried the beta site (https://beta.hospitalrun.io/) which is the same. Datepickers on other sites work fine it just doesn't seem to like this one.

**Comment by tangollama** [comment] 2016-05-10 17:03
Thanks @cmwebby. Are there any console log errors, etc?

**Comment by cmwebby** [comment] 2016-05-11 10:26
Hi @tangollama the only errors I'm getting are 4 x network errors - 
`Failed to load resource: the server responded with a status of 400 (Bad Request)` 

I also tried the beta site on my phone and tablet using chrome and the result was the same.

**Comment by tangollama** [comment] 2016-06-26 17:27
@jkleinsc and I have been unable to reproduce this issue. Adding this to Help Wanted so that someone in the community can look into the issue and try to provide additional validation / reproduction. We can't fix a bug that we can't reproduce :)

**Comment by mcoolidge** [comment] 2016-07-07 01:42
I also was unable to reproduce with Chrome Version 51.0.2704.103 m (64-bit)

**Comment by jglovier** [comment] 2016-07-08 14:55
Since nobody was able to reproduce this, I'm adding the `unable to reproduce` label and closing for now. Feel free to reopen if anyone can reproduce and provide steps to reproduce.

**Closed by jglovier** 2016-07-08 14:55 UTC
Labels: bug, Help Wanted, UX
