### ISSUE TITLE
UI issue in New surgical appointment End time minute list box

### ISSUE THREAD

**Issue by sskavitha** [HospitalRun/hospitalrun-frontend#1148] opened 2017-08-24 06:16 UTC
**Expected behavior:**
Alignment issue
**Actual behavior:**
Alignment issue
**Steps to reproduce:**
- Under scheduling section, Schedule surgery click new appointment,
- Minute box of end time value is not displaying fully.
**Screenshots (if applicable):**
Attached.
**OS and Browser:**
OS : 
![ui issue](https://user-images.githubusercontent.com/31200668/29652153-caae0c24-88c1-11e7-8bc9-ae37d369f1d6.png)
windows 8.1 pro

**Comment by tchan** [comment] 2017-08-24 10:49
I can't seem to replicate this. Seems to work fine on Chrome and the Electron App (mac). Is that the Windows Electron App (it's my first time seeing it) ?

I'll download it on my window machine to check as well.

**Comment by tchan** [comment] 2017-08-24 11:13
Seems to work fine on my windows machine. 
Although I'm running on 1920 x 1080 resolution
http://i.imgur.com/elK11px.png

Although if I lower it to 1440 x 900 I can replicate what you see so I guess it could be resolution related. 
http://i.imgur.com/TR0vRHb.png

**Comment by tangollama** [comment] 2017-08-31 12:48
@sskavitha I'm also unable to reproduce. Closing.

**Closed by tangollama** 2017-08-31 12:48 UTC
