### ISSUE TITLE
Tests pass even if they fail

### ISSUE THREAD

**Issue by tehKapa** [HospitalRun/hospitalrun-frontend#2287] opened 2020-08-12 07:59 UTC
## 🐛 Bug Report

- [ ] Tests pass even if they fail
- [ ] The tests fail. Understand why

Reference: https://github.com/HospitalRun/hospitalrun-frontend/runs/974788560?check_suite_focus=true#step:8:138

Cc @fox1t

**Comment by Tomastomaslol** [comment] 2020-08-14 04:18
Hi @tehKapa I took a look at this and it looks like it is caused by  asynchronous tests not using the `await` keyword to make sure that all asynchronous operations are closed when the expectation is fulfilled. If my understanding of the issue is correct the reason it doesn't fail the test is that expectation is still fulfilled even though operations are still happening in the background.

This can be fixed by going through all tests and making sure all asynchronous operations have closed before moving on to the next test. This would be a fairly big task so it might be worth exploring some other options before deciding how to approach this issue.

**Comment by fox1t** [comment] 2020-08-14 08:07
@Tomastomaslol nice finding! Would you love to make a PR?

**Comment by Tomastomaslol** [comment] 2020-08-15 02:13
Yeah sure. I will take a look at it! 🙂

**Comment by Tomastomaslol** [comment] 2020-08-29 04:16
The tests that keep generates the warnings were introduced in https://github.com/HospitalRun/hospitalrun-frontend/pull/2273/commits/41a97ad50328d975609483100014cbe0a66b0d16.

I created a branch that fixes the warnings but I keep having issues with this particular test: https://github.com/HospitalRun/hospitalrun-frontend/blob/master/src/__tests__/patients/search/SearchPatients.test.tsx#L33

Any attempt I tried so far to make sure the test does not have any asynchronous operations running after the test has been run has resulted in failures:

```bash

Summary of all failing tests
 FAIL  src/__tests__/patients/search/SearchPatients.test.tsx
  ● Search Patients › should update view patients table search request when patient search input changes

    expect(received).toEqual(expected) // deep equality

    - Expected
    + Received

      Object {
    -   "queryString": "someQueryString",
    +   "queryString": "",
      }

      50 | 
      51 |     const patientsTable = wrapper.find(ViewPatientsTable)
    > 52 |     expect(patientsTable.prop('searchRequest')).toEqual(expectedSearch)
         |                                                 ^
      53 |   })
      54 | })
      55 | 

      at Object.<anonymous> (src/__tests__/patients/search/SearchPatients.test.tsx:52:49)



``` 
Example code: https://github.com/HospitalRun/hospitalrun-frontend/compare/master...Tomastomaslol:2287_fix_async_tests?expand=1#diff-596c2918a23833fedf2fd54bae374b88R42

Unfortunately, I'm sure I understand the context well enough to be able to take a decision on how to proceed and make sure the test is verifying the behaviour correctly and get rid of the warnings. Any pointers or help from @jackcmeyer or anyone else would be greatly appreciated.

**Comment by yuktashres** [comment] 2020-11-19 17:12
Hello, is this still available to work on?

**Comment by tehKapa** [comment] 2020-11-20 19:57
Absolutely @yuktashres

**Comment by JacobMGEvans** [comment] 2021-01-14 15:30
#2516 Should fix this

**Comment by JacobMGEvans** [comment] 2021-01-16 02:22
@jackcmeyer I think this issue should be closed after a few days of reviewing the new testing environment and people have had a chance to mess around with it locally.

**Closed** 2021-01-16 18:28 UTC
Labels: LOE - large, in progress, 🐛bug
