### ISSUE TITLE
Patient ID sequence should not go backwards (greater to lesser)

### ISSUE THREAD

**Issue by mnorbeck** [HospitalRun/hospitalrun-frontend#485] opened 2016-06-01 12:23 UTC
It was observed and confirmed that at the Tebow hospital, the patient ID sequence was set at a number less than the greatest patient ID in the system.   There were 2000+ patients in the database currently, but the sequence was set at something around 1400.   It was not causing an issue, since the system prevented creation of patients with duplicate IDs.   However, in consult with @jkleinsc it was agreed that this behavior should be corrected.

**Comment by gnowoel** [comment] 2016-09-24 20:08
The suggested next patient ID is saved in the `sequence` model. However, if we use a custom ID in the form, the model won't update accordingly. For example, entering `P00010` for a suggested `P00005`, it would next time suggest `P00006` rather than `P00011`. Guess this is part of the reason why the sequence comes slower than the greatest patient ID.

A related problem happens when we cancel a new patient form. Because it's cancelled, the suggested ID is not used, but the number keeps getting incremented regardless. The sequence just goes too fast this time.

Not sure if these are root cause of what @mnorbeck encountered, but the situation shouldn't appear again once the sequence cached up with the greatest patient ID.

These two problems can be tackled separately, and I'd like to try sending a pull request for the second one first.

**Comment by mdarmani** [comment] 2016-10-08 21:56
Is this assigned? I don't see anyone assigned yet.

**Comment by jkleinsc** [comment] 2016-10-10 16:13
@mdarmani @gnowoel is working on this.

**Comment by jkleinsc** [comment] 2016-10-10 16:14
I am going to close this as #667 addressed this issue.  #572 is closing the loop on making sure dups can't be entered.

**Closed by jkleinsc** 2016-10-10 16:14 UTC
Labels: bug, Patient
