### ISSUE TITLE
ember-intl upgrade side effects

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#1561] opened 2018-11-17 05:01 UTC
**Expected behavior:**
Warning message should have no HTML in it.
**Actual behavior:**
Warning message has HTML in it.

**Steps to reproduce:**
_New Inventory Item Add_
1. Login
2. Click on Inventory Received 
3. Click on add button
4. View the message with HTML in it

OR 
_New Patient Quick Add_
1. Login
2. Click on Medication -> New Request
3. Enter patient name that doesn't exist
4. Fill in other information
5. View error message

**Screenshots (if applicable):**
_New Inventory Item Add_
![image](https://user-images.githubusercontent.com/18731800/48657187-81466880-e9f3-11e8-90a2-4ec29fd2b660.png)

_New Patient Quick Add_
![image](https://user-images.githubusercontent.com/18731800/48657427-2104f600-e9f6-11e8-82dc-b17f67afc7f0.png)

**OS and Browser:**
MacOS, Chrome 70, Firefox, Safari

- [x] warning messages which use HTML to render are showing the raw html in the message
- [x] unable to select first lanaguage
- [x] navigation bar items not being translated
- [ ] warnings with Hebrew in the console and some Hebrew messages not rendering
- [x] default to English for missing translations
- [x] different results between missing translations and empty translations
- [x] loss of support of right-to-left languages

**Comment by MatthewDorner** [comment] 2018-11-17 06:14
That's interesting, I'm not reproducing it. It just appears in a bold font. And I used Chromium 70 in Ubuntu.

**Comment by jackcmeyer** [comment] 2018-11-17 06:33
I was poking around in the translations files... 

Could it be related to the recent work on translations? After pulling in the most recent changes, I ran `npm install`

**Comment by MatthewDorner** [comment] 2018-11-17 06:37
I just realized my previous comment was using code before https://github.com/HospitalRun/hospitalrun-frontend/pull/1553. Just tried with the most recent code and now I'm reproducing, so yeah that must be it.

**Comment by jackcmeyer** [comment] 2018-11-17 06:38
I just went back to commit ee9bcc0fb3b2c2ae13c3ee90e1c7c937f01ef938 and was able to render the messages with the proper styling.

**Comment by jackcmeyer** [comment] 2018-11-17 06:42
Looks like this might be able to fix it: 
https://www.npmjs.com/package/ember-intl#format-html-message

**Comment by MatthewDorner** [comment] 2018-11-17 06:45
There appear to be a few other side-effects of the change to ember-intl:

- language select control doesn't work the same as before, not able to select the very top language (chinese? not sure)
- navigation bar items not being translated
- some warnings appear on npm start, but I tested the `appointments.messages.appointmentSaved` and `login.messages.signIn` one and they are still being displayed

**Comment by jackcmeyer** [comment] 2018-11-17 06:50
I did a quick test to fix the New Inventory Item message issue using `htmlSafe=true`. And it appears to work. 

Here is the change in `app/inventory/quick-add/template.hbs`

```
  <div class="alert alert-warning" role="alert">{{t 'inventory.messages.itemNotFound' item=model.name htmlSafe=true}}</div>
```

**Comment by jackcmeyer** [comment] 2018-11-17 06:57
@MatthewDorner 

Looks like the warning messages have to do with the 8th language in the list. I was not able to get the `appointments.messages.appointmentSaved` to work. 

The warning message has an Israeli flag, so I think the language is [Hebrew](https://www.google.com/search?safe=off&ei=mrvvW7eSH4qQjgTUrJ2wAw&q=hebrew+in+hebrew&oq=hebrew+in+hebrew&gs_l=psy-ab.3..0i71l8.3338.4575..4736...0.0..0.0.0.......0....1..gws-wiz.QfuLHW68JFY)

**Comment by MatthewDorner** [comment] 2018-11-17 07:00
Also we have lost the "default to English for missing translation" behavior, and we're getting different behavior if the translation key itself is missing from the JSON vs. if it is just a empty string, although that could be fixed with a script. Russian has a bunch of empty string translations but Thailand has a lot of missing ones.

![translation missing](https://user-images.githubusercontent.com/36939751/48658234-e904af80-ea03-11e8-9c87-57f5cf86d5e1.png)

**Comment by MatthewDorner** [comment] 2018-11-17 07:19
Well none of these things individually seem like they will be too hard to fix. If you'd like to work on it, I will be happy to help.

**Comment by jackcmeyer** [comment] 2018-11-17 07:30
Sure, I'd like to work on it!

**Comment by jackcmeyer** [comment] 2018-11-17 07:31
> language select control doesn't work the same as before, not able to select the very top language (chinese? not sure)

I was able to select the top language and see the translations take place. Any special steps to reproduce this one?

**Comment by MatthewDorner** [comment] 2018-11-17 07:44
Happens for me on Firefox and Chromium. I think it's because the action only happens when you change the selection. The actual difference is that before, the default selected value would be your current language, and now it's always defaulting to the first one instead:

![select control](https://user-images.githubusercontent.com/36939751/48658563-dee5af80-ea09-11e8-8a5f-a5b90ff860ad.png)

I'll start looking at the navigation bar not being translated issue.

**Comment by jackcmeyer** [comment] 2018-11-17 07:46
Gotcha. I'm looking at the HTML rendering one.

**Comment by chadian** [comment] 2018-11-17 07:58
This is related to my implementation of `ember-intl`. Sorry for the bugs that were introduced. I can investigate and work on some of these issues, too.

* The `htmlSafe` as you've discovered will fix any of the translations relying on html, this slipped my mind.
* The old translations had null for missing translations, I changed these to empty string because a null value wasn't allowed by `ember-intl`
* I will have to double-check what is happening with the select, it might need to pick the default value from the service on init.

**Comment by chadian** [comment] 2018-11-17 08:02
**Missing Translations**

To be consistent with missing translations we should probably:
1. Remove all empty strings and rely on the warnings of missing strings report at build time
2. Let missing translations fallback to the [missing translations message util](https://github.com/ember-intl/ember-intl/blob/master/docs/missing-translations.md):

```
// app/utils/intl/missing-message.js:

export default function missingMessage(key, locales, options) {
  throw new Error(`[ember-intl] Missing translation for key: "${key}" for locales: "${locales}"`);
}
```

What do you think?

**Comment by jackcmeyer** [comment] 2018-11-17 08:04
@chadian missing translations use to fall back to English. Is this still possible?

**Comment by MatthewDorner** [comment] 2018-11-17 08:10
We added the fall back to English pretty recently, and the change was made here: https://github.com/HospitalRun/hospitalrun-frontend/pull/1458.

I'd prefer keeping it that way since the error message doesn't help those trying to use the software, and we will be missing translations for a while.

**Comment by chadian** [comment] 2018-11-17 08:19
Ah yeah, that makes sense. I was just digging through the `ember-intl` issues and there's a solution that landed 3 weeks ago:
https://github.com/ember-intl/ember-intl/issues/584

Changing to:
`return run(() => this.set('intl.locale', [selectedLanguage, 'en']));` 
in `#setApplicationLanguage` `language-preference.js`.

Can you confirm that's the behavior you expect?

**Comment by MatthewDorner** [comment] 2018-11-17 08:37
Just tested myself, looks good!

**Comment by jackcmeyer** [comment] 2018-11-17 08:41
@MatthewDorner do you want us to open a PR for each task on this issue?

**Comment by MatthewDorner** [comment] 2018-11-17 08:50
Fewer PRs would be better, these don't look like they'll get too complicated individually.

**Comment by MatthewDorner** [comment] 2018-11-17 08:52
However if that makes it more confusing to keep track of who's doing what where, you can make them individually, doesn't really matter to me.

**Comment by chadian** [comment] 2018-11-17 08:55
I have a branch with a fix for:
- remove empty string translations
- setting a missing translation message to an empty string
- Adding the fallback locale

I can split them into separate PR's though.

**Comment by MatthewDorner** [comment] 2018-11-17 08:58
Together is fine if they're already together.

**Comment by jackcmeyer** [comment] 2018-11-17 08:59
I've got a branch for the `htmlSafe` and I'm trying to fix the hebrew translations

**Comment by chadian** [comment] 2018-11-17 20:36
Related to this issue and the migration to`ember-intl` was the loss of support for right-to-left languages. That's been added back as part of my #1562 pull request.

**Comment by chadian** [comment] 2018-11-19 09:50
@MatthewDorner Looks like my PR closed the issue, sorry about that. Maybe we can reopen it for the remaining checklist @jackcmeyer has setup and track the remaining issues.

*Missing translations*

As a follow up to the question from @MatthewDorner about missing translations in these files I think we will need some sort of tooling. I was thinking we can use `en.json` as a source of truth and then maybe flatten the structure into something like:

`flatten_en_reference.json`
```
{
  "admin.address.address1Label": "Address 1 Label"
}
```

`flatten_fr_missing.json`
```
{
  "admin.address.address1Label": ""
}
```

Only missing from `en.json` would should up in the flattened. We would be able to run the reverse feed of the `flatten_fr_missing.json` back into the `fr.json`. If there are any tools that do something similar out of the box that would be nice, too.

I have a few friends that can help out with a few of the missing translations and have reached out already so if we could get a friendlier format we could fill in a bit of what's missing.

*Urdu font change when switching to `ember-intl`*
I am not sure why it changed, but maybe first we can verify if it's something that changes the meaning, context, readability, usability of the app? If it's okay we can just leave it, otherwise I can create an issue and investigate further.

**Comment by jackcmeyer** [comment] 2018-11-19 20:38
@chadian and @MatthewDorner I've updated the task list to align with items that have been fixed and merged to master.

**Comment by chadian** [comment] 2018-11-20 10:10
@jackcmeyer I think "unable to select first language" was fixed in my PR:
https://github.com/HospitalRun/hospitalrun-frontend/pull/1562/files#diff-4a152be7cf0c07e5f4bde6a37a912d69R56

(at least I hope so!)

**Comment by jackcmeyer** [comment] 2018-11-20 17:03
@chadian sorry, must have missed this. I've also updated the list after my PR was merged. Last thing to do is the Hebrew translation warnings.

**Comment by MatthewDorner** [comment] 2018-11-21 03:30
Yeah that one was fixed.

**Comment by MatthewDorner** [comment] 2018-11-24 04:43
I was trying to get hospitalrun-server working with a current frontend. So I built the frontend with `ember build --environment=production`, copied to `prod` folder, and pointed the frontend npm dependency in hospitalrun-server to my git branch with my new build, but I am getting this error when I try to access the app running with hospitalrun-server:

![sourcemap error](https://user-images.githubusercontent.com/36939751/48962980-cec05980-ef4e-11e8-8043-9fb0db90088b.png)

It's the same error whether or not I enable sourcemaps in ember-cli-build.js, though we've had them disabled so far. It works however if I do the build without `--environment=production`.

**Comment by MatthewDorner** [comment] 2018-11-27 05:02
Regarding the above, I think I have it fixed by changing broccoli-serviceworker `excludePaths` setting in config/environment.js, will PR after testing a little more.

**Closed** 2019-11-05 09:31 UTC
Labels: wontfix
