### ISSUE TITLE
move from jade to pug

### ISSUE THREAD

**Issue by tangollama** [HospitalRun/hospitalrun-frontend#1159] opened 2017-09-01 13:35 UTC
**Expected behavior:**
npm install with no warning

**Actual behavior:**
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade

**Steps to reproduce:**
checkout the project
navigate to the frontend directory
npm install

**Screenshots (if applicable):**
N/A

**OS and Browser:**

**Comment by zzbazinga** [comment] 2017-09-02 05:59
Got these warning while npm install.
Attaching screenshot
![screenshot from 2017-09-02 11-27-51](https://user-images.githubusercontent.com/29006655/29993332-ee8be9b0-8fd1-11e7-809b-7329a32f6f83.png)

**Comment by baoqchau** [comment] 2017-09-03 23:09
Hi @tangollama, are we still using jade (or pug) in our project? Because I cannot find jade package in `package.json` and as I know, HospitalRun using Handlebars as view engine, not Jade

**Comment by guillaume-ro-fr** [comment] 2017-10-04 19:15
Hi @baoqchau !

Here the dependancies tree : 

```
hospitalrun@1.0.0-beta /Users/guillaume/Desktop/hospitalrun-frontend
└─┬ electron-prebuilt-compile@1.6.2
  └─┬ electron-compilers@5.9.0
    └── jade@1.11.0
```

**Comment by jbryson3** [comment] 2018-02-08 19:33
I do not get this warning on MacOS with npm 5.5.1 (node 8.9.3)

The only warning I see is:
```npm WARN The package electron-protocol-serve is included as both a dev and production dependency.```

**Comment by baldyjohnmichael** [comment] 2018-03-18 14:36
Mind if I work on this?

**Comment by baoqchau** [comment] 2018-03-18 15:48
@baldyjohnmichael go ahead

**Comment by stukalin** [comment] 2018-03-19 08:37
@baldyjohnmichael sure you can take over this issue. However, the problem is (sorry if I say obvious things here) that you need to go down the dependency tree and replace `jade` in the `electron-compilers`. Actually there are a couple of PRs there, but they were not merged. If you were able to push them, you'd have the issue half-done.
https://github.com/electron-userland/electron-compilers/pull/34
https://github.com/electron-userland/electron-compilers/pull/66

**Closed** 2019-08-07 13:18 UTC
Labels: Help Wanted, LOE: < 1 week, wontfix
