### ISSUE TITLE
Persisting Data To Couch When Notifications Are Disabled

### ISSUE THREAD

**Issue by evandropj** [HospitalRun/hospitalrun-frontend#1452] opened 2018-06-29 18:31 UTC
I installed the hospitalrun-frontend, but the data is not staying saving when I restart the server.
Anyone know how can I solve this trouble?

**Comment by MatthewDorner** [comment] 2018-07-02 02:59
You're just running frontend? If your frontend can't communicate with your database, data is stored in your browser storage until it can connect again and sync. Is it possible your browser cache was cleared? You can also make sure your database is running by going to http://localhost:5984/_utils and make sure you see the database admin panel there.

**Comment by evandropj** [comment] 2018-07-05 00:33
Yes, my database is running, but I believe that the data stay storage only in cache, because when I restart the server the data is cleaning.

**Comment by MatthewDorner** [comment] 2018-07-05 00:56
You should be able to see the data records in the database admin panel, by logging in with the default user:couchadmin pass:test. If it's erasing from there, it's something with your database. Are you using a docker couchdb setup or regular setup, and which couchdb version? Also if you want to join the Slack at https://hospitalrun.slack.com I can look at it with you over a screen sharing session.

**Comment by evandropj** [comment] 2018-07-06 21:55
Yes, I can see the data records in the database and it is stay there when I restart the server, but I'm not able to see the same data in the front-end when I restart the server.
I'm using couchDB 1.6 and regular setup.

**Comment by MatthewDorner** [comment] 2018-07-06 22:14
Any errors in your browser's javascript console when you log in to hospitalrun or shortly after?

**Comment by MatthewDorner** [comment] 2018-08-02 04:35
This could be the same thing as https://github.com/HospitalRun/hospitalrun-server/issues/112.

Can you try again, making sure to accept your browser's request to allow push notification?

**Comment by donaldwasserman** [comment] 2018-08-21 03:58
From [#112 on the server](https://github.com/HospitalRun/hospitalrun-server/issues/112)
it's happening if I use Firefox, but not Chrome. To reproduce:

- start with a database having >0 patients in it
- close HospitalRun tab and erase Firefox browser cache
- log in to HospitalRun, view list of patients. It will (incorrectly) show 0 patients. waiting for the database to sync doesn't seem to make any difference.
- add a patient. it will get P00001 even if that ID is already in use
- you will now also be able to see all the patients

same thing happens with inventory items. good thing you noticed, I will try to figure it out.

**Comment by fox1t** [comment] 2019-08-07 20:29
This fix is out of scope for the version 2.0.0 since it will be built ground up.

**Closed by fox1t** 2019-08-07 20:29 UTC
Labels: Help Wanted
