### ISSUE TITLE
Patient Id auto increment with page refresh

### ISSUE THREAD

**Issue by sentana** [HospitalRun/hospitalrun-frontend#447] opened 2016-05-09 07:08 UTC
**Expected behavior:**
Patient ID should increment every time a patient is registered successfully.
**Actual behavior:**
The patient ID increment even if we cancel the registration 
**Steps to reproduce:**
1. Click the new patient menu, and new patient registration form is open.
2. Take a note of the Patient ID
3. Click a Go Back arrow and Click Go Forward arrow
4. Notice the ID increments 

**Screenshots (if applicable):**

**OS and Browser:**

**Comment by tangollama** [comment] 2016-05-10 17:00
@jkleinsc we've talked about this before. Do we consider this a true defect or not? I'm curious what others think.

**Comment by jkleinsc** [comment] 2016-05-10 19:10
@tangollama this is a duplicate of #245

**Comment by ninjacatt** [comment] 2017-03-25 10:00
since this is duped to #245 , should we close this too?

**Comment by jkleinsc** [comment] 2017-03-25 10:39
@ninjacatt yes this should be closed.

**Closed by jkleinsc** 2017-03-25 10:39 UTC
Labels: Help Wanted, Needs Requirements, Patient
