### ISSUE TITLE
Build acceptance test for appointments.missed

### ISSUE THREAD

**Issue by billybonks** [HospitalRun/hospitalrun-frontend#691] opened 2016-10-02 05:45 UTC
In order to effectively use the no missing translations test, we need to make sure that every page is visited during acceptance tests.

This issue tracks the missing `appointments.missed` acceptance test

for ember new commers the value `some.route` is the route that's missing you can find them under router.js

**Comment by migbar** [comment] 2016-10-07 09:39
@billybonks, I was trying to pick up these missing acceptance tests issues, but then saw that some or most do in fact exist  https://github.com/HospitalRun/hospitalrun-frontend/blob/master/tests/acceptance/appointments-test.js#L27

So I am pretty sure I am missing something.

**Comment by emadehsan** [comment] 2017-03-31 01:27
@billybonks I think test for this exists as @migbar suggested
https://github.com/HospitalRun/hospitalrun-frontend/blob/master/tests/acceptance/appointments-test.js#L31-L50

**Comment by jkleinsc** [comment] 2017-03-31 20:32
@migbar and @emadehsan you are correct.  I will close this issue.

**Comment by BogdanAlexandru** [comment] 2017-03-31 21:32
@jkleinsc 
The test implemented there never appears to visit `/appointments/missed`, instead goes to `/appointments`. The real application visits `/appointments/missed`.

Is that intended? I looked into this a couple of days ago and made it go to `/appointments/missed`, but missed appointments wouldn't show. I didn't get the chance to debug it.

**Comment by jkleinsc** [comment] 2017-04-05 15:01
@BogdanAlexandru I "missed" that 😄 !  I'll reopen the issue.  I just took a quick look and I think the problem is that the missed appointments only shows this weeks missed appointments, so if the appointment wasn't for this week, it will not show up.  I am going to add another issue to add a date filter for missed appointments.

**Comment by jkleinsc** [comment] 2017-04-05 15:06
@BogdanAlexandru I just realized that the missed appointments functionality can be entirely done via the appointments search screen.  I would change the test to use that screen (eg appointments/search?startDate=1491192000000&status=Missed) instead of the appointments/missed URL.  I don't think we need a separate menu option for appointments/missed and am going to log an issue to remove that menu option.

**Closed** 2017-04-20 01:18 UTC
Labels: Appointments, Help Wanted
