### ISSUE TITLE
Reporting feature for billing and invoices

### ISSUE THREAD

**Issue by morrismusumi** [HospitalRun/hospitalrun-frontend#1356] opened 2018-01-29 13:20 UTC
**Expected behavior:**

**Actual behavior:**
No reporting feature in Billing

**Steps to reproduce:**

**Screenshots (if applicable):**

**OS and Browser:**

**Comment by donaldwasserman** [comment] 2018-08-02 03:31
Closing for now since this is a duplicate of many feature requests.

**Closed by donaldwasserman** 2018-08-02 03:31 UTC
Labels: duplicate, feature-proposal
