### ISSUE TITLE
System wide currency configuration

### ISSUE THREAD

**Issue by taras** [HospitalRun/hospitalrun-frontend#678] opened 2016-09-27 19:59 UTC
**Expected behavior:**
We need to have a standard way to manage currency formatting for the entire application. We just merged #668 which provide a number field that we can use to allow users to input numbers. We could wire a new service into that input field to ensure that input values are sanitized correctly.

**Actual behavior:**
All locals are using $ as currency symbol.

Let's hash out all of the requirements around this service and everything that'll need to be implemented to make it happen.

## Questions:

1. What library can we use to provide output formatting and input sanitization?
2. How do we wire this into existing localization?
3. How do we find all of the currency fields?

/cc @jkleinsc @wolfieorama

**Comment by BogdanAlexandru** [comment] 2016-10-02 14:20
Does this not intersect (replace?) https://github.com/HospitalRun/hospitalrun-frontend/issues/314?

**Comment by jkleinsc** [comment] 2016-10-03 13:46
@BogdanAlexandru you are correct.  This is duplicate of #314.  

@taras @wolfieorama I would like to close this as a duplicate of #314.

**Comment by jkleinsc** [comment] 2016-10-10 18:01
Closing as duplicate of #314

**Closed by jkleinsc** 2016-10-10 18:01 UTC
